### ISSUE TITLE
mutagen.mp3.HeaderNotFoundError: can't sync to an MPEG frame

### ISSUE THREAD

**Issue by magne4000** [thebigmunch/gmusicapi-scripts#32]
Missing MPEG frame make the whole process fail.
```
Traceback (most recent call last):
  File "/home/magne/workspace/gmusicapi-scripts/gmsync.py", line 202, in <module>
    main()
  File "/home/magne/workspace/gmusicapi-scripts/gmsync.py", line 164, in main
    upload_songs = compare_song_collections(local_songs, google_songs)
  File "/home/magne/workspace/gmusicapi-scripts/gmwrapper.py", line 49, in compare_song_collections
    src_key = create_song_key(src_song)
  File "/home/magne/workspace/gmusicapi-scripts/gmwrapper.py", line 68, in create_song_key
    song = song if isinstance(song, dict) else _mutagen_fields_to_single_value(song)
  File "/home/magne/workspace/gmusicapi-scripts/gmwrapper.py", line 35, in _mutagen_fields_to_single_value
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 235, in File
    return Kind(filename)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/_file.py", line 40, in __init__
    self.load(filename, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/id3/__init__.py", line 1084, in load
    self.info = self._Info(fileobj, offset)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/mp3.py", line 132, in __init__
    self.__try(fileobj, offset, size - offset, False)
  File "/usr/local/lib/python2.7/dist-packages/mutagen/mp3.py", line 170, in __try
    raise HeaderNotFoundError("can't sync to an MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to an MPEG frame
```

**Comment by thebigmunch** [comment]
Duplicate issue. Try my suggestion in https://github.com/thebigmunch/gmusicapi-scripts/issues/29.

**Comment by magne4000** [comment]
I do not fully agree that this is the same use case.
There are files that can be corrupted, and I think that just adding a try/catch block can fix this particular case. Not syncing a 18000 songs library just because of an Exception seems a little exagerated.

**Comment by thebigmunch** [comment]
You obviously didn't bother to do as asked or read through my comment on the linked issue or any of the related changes. Why waste my time?
