### ISSUE TITLE
oauth.cred

### ISSUE THREAD

**Issue by swmiller6** [thebigmunch/gmusicapi-scripts#33]
For some reason I am unable to create the oauth.cred file on first run. It prompts for the google code which I supply but fails after with the following message. 
2015-05-12 14:12:12,731 - gmusicapi.Musicmanager1 (musicmanager:176) [WARNING]: could not retrieve oauth credentials from '/home/$USERNAME/.local/share/gmusicapi/oauth.cred'
No handlers could be found for logger "oauth2client.util"

Visit the following url:
 https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusicmanager&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=652850857958.apps.googleusercontent.com&access_type=offline
Follow the prompts, then paste the auth code here and hit enter: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Unable to login with specified oauth code.
2015-05-12 14:12:15,129 - gmusicapi.Musicmanager1 (musicmanager:176) [WARNING]: could not retrieve oauth credentials from '/home/$USERNAME/.local/share/gmusicapi/oauth.cred'
Sorry, login failed.
Loading Google Music songs...
Traceback (most recent call last):
  File "./gmsync.py", line 202, in <module>
    main()
  File "./gmsync.py", line 159, in main
    google_songs = mmw.get_google_songs()
  File "/home/swmiller6/gmusicapi-scripts/gmwrapper.py", line 399, in get_google_songs
    songs = self.api.get_uploaded_songs()
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/clients/musicmanager.py", line 275, in get_uploaded_songs
    to_return = [song for chunk in to_return for song in chunk]
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/clients/musicmanager.py", line 303, in _get_all_songs
    lib_chunk.continuation_token)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/protocol/shared.py", line 206, in perform
    req_kwargs = cls.build_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/protocol/shared.py", line 87, in build_request
    val = val(*args, **kwargs)
  File "<string>", line 2, in dynamic_data
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/protocol/musicmanager.py", line 65, in pb
    msg = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-4.0.0-py2.7.egg/gmusicapi/protocol/musicmanager.py", line 607, in dynamic_data
    msg.client_id = client_id
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0_alpha_2-py2.7.egg/google/protobuf/internal/python_message.py", line 504, in field_setter
  File "/usr/local/lib/python2.7/dist-packages/protobuf-3.0.0_alpha_2-py2.7.egg/google/protobuf/internal/type_checkers.py", line 161, in CheckValue
TypeError: None has type <type 'NoneType'>, but expected one of: (<type 'str'>, <type 'unicode'>)

**Comment by thebigmunch** [comment]
Seems I forgot to respond to this. This clearly has nothing to do with my code. It's either a local issue or a gmusicapi issue.
