### ISSUE TITLE
issue while uploading

### ISSUE THREAD

**Issue by matigonkas** [thebigmunch/gmusicapi-scripts#36]
i was trying to upload songs and i got this error 
```
python gmupload.py /media/extssd/musicdl
13
Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 18 local songs.

Uploading 18 songs to Google Music

Traceback (most recent call last):ajor Lazer - Free The Universe 2013 Electronic 320kbps CBR MP3 [VX]/01 Major Lazer - You're No Good (feat. Santigold, Vybz Kartel, Danielle Haim & Yasmin).mp3
  File "gmupload.py", line 94, in <module>
    main()
  File "gmupload.py", line 84, in main
    mmw.upload(upload_songs, enable_matching=cli['match'])
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 582, in wrapper
    return function(*args, **kw)
  File "/home/supergonkas/gmusicapi/gmwrapper.py", line 463, in upload
    uploaded, matched, not_uploaded = self.api.upload(file, transcode_quality="320k", enable_matching=enable_matching)
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 582, in wrapper
    return function(*args, **kw)
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 559, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 412, in upload
    raise NotLoggedIn("Not authenticated as an upload device;"
gmusicapi.exceptions.NotLoggedIn: Not authenticated as an upload device; run Api.login(...perform_upload_auth=True...) first.
```
how do i login?

**Comment by thebigmunch** [comment]
Have you already enabled Google Music on your Google account?

**Comment by matigonkas** [comment]
yes @thebigmunch  but i didnt put my details in anywhere .Where should i put them?

**Comment by thebigmunch** [comment]
If you try to login without using my scripts, does it work?

**Comment by matigonkas** [comment]
@thebigmunch im not understaning ,where do i login? in your script,in the browser?

**Comment by thebigmunch** [comment]
I mean just using [gmusicapi](https://github.com/simon-weber/gmusicapi) directly. If you can't do that much, I won't really be able to help you.

**Comment by matigonkas** [comment]
@thebigmunch  can you guide me on how do i do it?

**Comment by matigonkas** [comment]
@thebigmunch  Somehow its now working ,it propmted with link i put the code and it worked
Thanks for your help ,and sorry for wasting your time :P
