### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Rika-chan** [thebigmunch/gmusicapi-scripts#42]
```
Scanning for missing songs...
Traceback (most recent call last):
  File "./gmsync.py", line 202, in <module>
    main()
  File "./gmsync.py", line 164, in main
    upload_songs = compare_song_collections(local_songs, google_songs)
  File "/home/rika-chan/gmusicapi-scripts-master/gmwrapper.py", line 49, in compare_song_collections
    src_key = create_song_key(src_song)
  File "/home/rika-chan/gmusicapi-scripts-master/gmwrapper.py", line 68, in create_song_key
    song = song if isinstance(song, dict) else _mutagen_fields_to_single_value(song)
  File "/home/rika-chan/gmusicapi-scripts-master/gmwrapper.py", line 35, in _mutagen_fields_to_single_value
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
  File "/home/rika-chan/gmusicapi-scripts-master/gmwrapper.py", line 35, in <dictcomp>
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
IndexError: list index out of range
```

Using debian 7.

**Comment by ciaran-c** [comment]
Same here, Ubuntu 14.04

**Comment by Rika-chan** [comment]
Closing, dev branch works fine.

**Comment by thebigmunch** [comment]
Yeah, I've been running out of time/motivation to push a release to PyPI. This was fixed a while ago in the devel branch. For anyone curious, it's caused by an empty tag field from a local file which my code didn't handle.
