### ISSUE TITLE
gmsync: Scanning for missing songs: list index out of range

### ISSUE THREAD

**Issue by bong0** [thebigmunch/gmusicapi-scripts#48]
When calling gmsync like this:

`./gmsync.py up -a -U 'B8:27:EB:FF:FF:FF' -d ~/sc_music/ `

it crashes as follows:
```
Scanning for missing songs...
Traceback (most recent call last):
  File "./gmsync.py", line 202, in <module>
    main()
  File "./gmsync.py", line 164, in main
    upload_songs = compare_song_collections(local_songs, google_songs)
  File "/home/syncer/gmusicapi-scripts/gmwrapper.py", line 49, in compare_song_collections
    src_key = create_song_key(src_song)
  File "/home/syncer/gmusicapi-scripts/gmwrapper.py", line 68, in create_song_key
    song = song if isinstance(song, dict) else _mutagen_fields_to_single_value(song)
  File "/home/syncer/gmusicapi-scripts/gmwrapper.py", line 35, in _mutagen_fields_to_single_value
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
  File "/home/syncer/gmusicapi-scripts/gmwrapper.py", line 35, in <dictcomp>
    return {k: v[0] for k, v in mutagen.File(file, easy=True).iteritems()}
IndexError: list index out of range
```

**Comment by thebigmunch** [comment]
Previously, I would have had to tell you to use the devel version, but I finally released it to PyPI. So just use the [installation instructions](https://github.com/thebigmunch/gmusicapi-scripts#installation) to install the new stable release where this problem is solved.

**Comment by bong0** [comment]
After having reinstalled pip and
