### ISSUE TITLE
Error finishing song upload

### ISSUE THREAD

**Issue by mchugh19** [thebigmunch/gmusicapi-scripts#49]
Howdy, 

Maybe this is a rare case of a google server being unavailable, but it appears I am unable to reach the uploadsj server, and thus unable to check on the status of an upload. 

When I attempt to upload an mp3, gmupload seems to start it off, but never returns. After it fails, or I ctrl-c to try again, the second time I attempt to to upload the same song, I get a message that it already exists. But the failure of checking upload status means I can only upload a song at a time, wait for the timeout, and then run gmupload again on the next song.

In starting to troubleshoot this issue, I tried running a plain curl on uploadsj.clients.google.com which also just timesout. Is it possible google moved their upload endpoint? 

Here is the output from running an upload for a single song.
```
$ gmupload /storage/music/song.mp3 
Successfully logged in.

Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 1 local songs.

Uploading 1 song(s) to Google Music

Traceback (most recent call last):
  File "/usr/local/bin/gmupload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_scripts/gmupload.py", line 141, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 503, in upload
    for result in self._upload(filepaths, enable_matching=enable_matching, transcode_quality=transcode_quality):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 458, in _upload
    uploaded, matched, not_uploaded = self.api.upload(filepath, enable_matching=enable_matching, transcode_quality=transcode_quality)
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 590, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 526, in upload
    track, path, server_id, do_not_rematch)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 231, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fdd036faed0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

Here is the output from attempting to sync a directory of songs

```
$ gmsync /storage/music/songdir/
Successfully logged in.

Loading Google Music songs...
Filtered 0 Google Music songs
Loaded 1803 Google Music songs

Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 1 local songs.

Scanning for missing songs...

Uploading 1 song(s) to Google Music

Traceback (most recent call last):
  File "/usr/local/bin/gmsync", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_scripts/gmsync.py", line 223, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 503, in upload
    for result in self._upload(filepaths, enable_matching=enable_matching, transcode_quality=transcode_quality):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 458, in _upload
    uploaded, matched, not_uploaded = self.api.upload(filepath, enable_matching=enable_matching, transcode_quality=transcode_quality)
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "<string>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 590, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 526, in upload
    track, path, server_id, do_not_rematch)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 208, in perform
    response = session.send(req_kwargs, cls.required_auth)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 86, in send
    res = self._send_with_auth(req_kwargs, desired_auth, rsession)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/session.py", line 231, in _send_with_auth
    return rsession.request(**req_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='uploadsj.clients.google.com', port=443): Max retries exceeded with url: /uploadsj/scottyagent (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f15709209d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
```

**Comment by thebigmunch** [comment]
If it's not something related to Google's server, then it looks like it could be related to #46 and #47 where you'll find a link to the appropriate gmusicapi issue. As per that issue, I'm able to upload some songs but not others unless they are stripped of their metadata. Hopefully Simon gets to implement the new id generation soon.

**Comment by mchugh19** [comment]
Cool cool. Just to clarify, I'm not seeing either of those errors. Attempting to upload an mp3 appears to work, it's the upload progress/verification that isn't responding. The upload effectively hangs on the first song, which results in a timeout reaching the server. 

It sounds like this may be an issue with gmusicapi, so I'll file the bug report there. 

Thanks!

**Comment by thebigmunch** [comment]
Yeah, before posting anything here, I would always check to see if doing uploading directly via gmusicapi in the interpreter results in the same. If it does, then it's definitely not on my end.
