### ISSUE TITLE
Unable to find a way to authenticate for upload

### ISSUE THREAD

**Issue by jonathanthomas83** [thebigmunch/gmusicapi-scripts#50]
Thanks for this great work, looks great and just what I need.

Running Ubuntu server and have all the latest code installed, can do a gmsearch and am prompted for credentials, but no prompts when doing an upload, what am I missing? On the usage, you mention a link to get an auth code, but I don't get the link either. Many thanks for your time.

Get the following output when trying to do a gmupload.

Loading local songs...
Excluded 0 local songs.
Filtered 0 local songs.
Loaded 27118 local songs.

Uploading 27118 song(s) to Google Music

Traceback (most recent call last):
  File "/usr/local/bin/gmupload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_scripts/gmupload.py", line 141, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "<decorator-gen-118>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 503, in upload
    for result in self._upload(filepaths, enable_matching=enable_matching, transcode_quality=transcode_quality):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi_wrapper/gmusicapi_wrapper.py", line 458, in _upload
    uploaded, matched, not_uploaded = self.api.upload(filepath, enable_matching=enable_matching, transcode_quality=transcode_quality)
  File "<decorator-gen-64>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 613, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-63>", line 2, in upload
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/utils/utils.py", line 590, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/musicmanager.py", line 412, in upload
    raise NotLoggedIn("Not authenticated as an upload device;"
gmusicapi.exceptions.NotLoggedIn: Not authenticated as an upload device; run Api.login(...perform_upload_auth=True...) first.

**Comment by thebigmunch** [comment]
Check to see if you have an ``oauth.cred`` file in the [appropriate directory](https://unofficial-google-music-api.readthedocs.org/en/latest/reference/musicmanager.html#gmusicapi.clients.Musicmanager.perform_oauth). If so, delete it and try again. Or, if you specified a different credential file (you didn't provide the commandline), do the same.

Fair warning, you're probably unlikely to succeed in most uploads due to #47 that is waiting on an upstream fix.

**Comment by jonathanthomas83** [comment]
@thebigmunch That's great, thank you for your time. Will give it a try when the upstream fix goes in.

**Comment by thebigmunch** [comment]
FYI, this has been fixed for a bit in gmusicapi. Have you resolved this issue?

**Comment by thebigmunch** [comment]
Closing. If it needs to be re-opened, post a comment.
