### ISSUE TITLE
TypeError on execution in protobuf

### ISSUE THREAD

**Issue by jcrevier** [thebigmunch/gmusicapi-scripts#56]
I've spent some time trying to get this working now that python 2 has been depreciated, and I've run into some trouble. Seems to be related to Google Protocol Buffer support for python 3. Have I missed something obvious that I should do to avoid this? 

```
[joel@FedoraVM logs]$ gmsync up -f 'artist:leaf' /mnt/media/music/Music
Traceback (most recent call last):
  File "/usr/bin/gmsync", line 7, in <module>
    from gmusicapi_scripts.gmsync import main
  File "/usr/lib/python3.4/site-packages/gmusicapi_scripts/gmsync.py", line 62, in <module>
    from gmusicapi_wrapper import MusicManagerWrapper
  File "/usr/lib/python3.4/site-packages/gmusicapi_wrapper/__init__.py", line 11, in <module>
    from . import utils
  File "/usr/lib/python3.4/site-packages/gmusicapi_wrapper/utils.py", line 9, in <module>
    from gmusicapi.utils.utils import accept_singleton
  File "/usr/lib/python3.4/site-packages/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "/usr/lib/python3.4/site-packages/gmusicapi/clients/__init__.py", line 3, in <module>
    from gmusicapi.clients.musicmanager import Musicmanager, OAUTH_FILEPATH
  File "/usr/lib/python3.4/site-packages/gmusicapi/clients/musicmanager.py", line 23, in <module>
    from gmusicapi.protocol import musicmanager, upload_pb2, locker_pb2
  File "/usr/lib/python3.4/site-packages/gmusicapi/protocol/musicmanager.py", line 25, in <module>
    from gmusicapi.protocol import upload_pb2, locker_pb2, download_pb2
  File "/usr/lib/python3.4/site-packages/gmusicapi/protocol/upload_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/usr/lib/python3.4/site-packages/google/protobuf/descriptor_pb2.py", line 243, in <module>
    has_default_value=False, default_value=str("", "utf-8"),
TypeError: decoding str is not supported
```

For the record, 

```
[joel@FedoraVM logs]$ python -V
Python 2.7.10
[joel@FedoraVM logs]$ python3 -V
Python 3.4.3
[joel@FedoraVM logs]$ python3 -m pip show protobuf
Metadata-Version: 2.0
Name: protobuf
Version: 3.0.0b2.post1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /usr/lib/python3.4/site-packages
Requires: six, setuptools
[joel@FedoraVM logs]$
```

**Comment by jcrevier** [comment]
After messing around a bit, I was able to get it to work by downgrading protobuf to 3.0.0b1.

```sudo python3 -m pip install protobuf==3.0.0b1```
  
Seems like [3.0.0b2 ](https://github.com/google/protobuf/releases/tag/v3.0.0-beta-2)breaks something.

**Comment by thebigmunch** [comment]
No, 3.0.0b2.post1 breaks something. 3.0.0b2 should work fine. This is an upstream issue having nothing to do with my scripts, though. Next gmusicapi release should make sure post1 isn't used.

**Comment by jcrevier** [comment]
Yep. I see that now. Thanks :)
