### ISSUE TITLE
gmdownload "Sorry, login failed" ssl.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:600)

### ISSUE THREAD

**Issue by dazzag24** [thebigmunch/gmusicapi-scripts#57]
```
$ gmdownload  -f artist:Halsey
__init__() takes at most 4 positional arguments (5 given)

Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusicmanager&access_type=offline&client_id=XXXXXXXXXXX.apps.googleusercontent.com&response_type=code
Follow the prompts, then paste the auth code here and hit enter: xxxREDACTEDxxxx

Unable to login with specified oauth code.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi_wrapper/musicmanager.py", line 50, in login
    self.api.perform_oauth(storage_filepath=oauth_cred)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/musicmanager.py", line 97, in perform_oauth
    credentials = flow.step2_exchange(code)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 2103, in step2_exchange
    headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python3.4/dist-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python3.4/dist-packages/httplib2/__init__.py", line 987, in _conn_request
    conn.connect()
  File "/usr/lib/python3.4/http/client.py", line 1287, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.4/ssl.py", line 362, in wrap_socket
    _context=self)
  File "/usr/lib/python3.4/ssl.py", line 580, in __init__
    self.do_handshake()
  File "/usr/lib/python3.4/ssl.py", line 807, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:600)
Sorry, login failed.
```

Using Ubuntu 15.10 with gmusicapi-scripts installed as per instructions here: 
https://thebigmunch.github.io/gmusicapi-scripts/install/

Any help on how to solve this one is much appreciated.

Thanks

**Comment by thebigmunch** [comment]
The ``__init__() takes at most 4 positional arguments (5 given)`` is strange; I have no idea where that would come from at that point. Are you running this as root? If so, try running it as a regular user.

**Comment by thebigmunch** [comment]
Closing for lack of response.
