### ISSUE TITLE
UnicodeEncodeError when downloading songs

### ISSUE THREAD

**Issue by dvcrn** [thebigmunch/gmusicapi-scripts#68]
I have a lot of German, Japanese and Korean songs including a lot of special characters in my library and am currently trying to automatically download them to my machine. The english songs pass fine but the rest seems to fail:

```
Traceback (most recent call last):
  File "/home/backup/backup-scripts/virtualenv/bin/gmsync", line 11, in <module>
    sys.exit(main())
  File "/home/backup/backup-scripts/virtualenv/lib/python3.4/site-packages/gmusicapi_scripts/gmsy$
c.py", line 150, in main
    mmw.download(songs_to_download, template=cli['output'])
  File "/home/backup/backup-scripts/virtualenv/lib/python3.4/site-packages/wrapt/wrappers.py", lin
e 561, in __call__
    args, kwargs)
  File "/home/backup/backup-scripts/virtualenv/lib/python3.4/site-packages/gmusicapi_wrapper/decor
ators.py", line 22, in wrapper
    return function(*args, **kwargs)
  File "/home/backup/backup-scripts/virtualenv/lib/python3.4/site-packages/gmusicapi_wrapper/music
manager.py", line 215, in download
    for result in self._download(songs, template):
  File "/home/backup/backup-scripts/virtualenv/lib/python3.4/site-packages/gmusicapi_wrapper/music
manager.py", line 176, in _download
    os.makedirs(dirname)
  File "/home/backup/backup-scripts/virtualenv/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 40: ordinal not in range(128)
```

Using python3.4 in virtualenv

**Comment by thebigmunch** [comment]
Please always post full tracebacks; it usually helps to know where in the code things happen.

I believe '\xfc' is actually an umlaut (ü) in the latin-1 encoding. What locale is set on your system?

**Comment by dvcrn** [comment]
Apologies for the lack of information. The script runs automatically on a backup system and the stack trace was exposing too much information about the setup. I was in a rush yesterday and didn't have time to filter some things out. I updated the initial post 👍 

But good news, the locale was indeed the issue! The debian it was running on had locales incorrectly setup. After re-generating and setting the correct locales the problem disappeared. 

Thanks for the fast answer!
