### ISSUE TITLE
I have Python 3.4 but get "gmusicapi-wrapper does not support this version of Python"

### ISSUE THREAD

**Issue by Night-Man** [thebigmunch/gmusicapi-scripts#69]
In Ubuntu 14.04 I have both python 2.7 and 3.4 installed but when I try to install this with pip I get this "gmusicapi-wrapper does not support this version of Python" error.

**Comment by thebigmunch** [comment]
Make sure you're running it with 3.4 and not 2.7.

**Comment by Night-Man** [comment]
Ok, I think I've got that figured out but it's still giving me an error for the wrong version of setuptools.

````
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 3.3 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=11.3'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gmupload", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 3.3 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=11.3'))
````

I've tried installing setuptools through pip but for whatever reason is doesn't help. And when I install it through apt-get it installs version 3.3 and gives me this error.
