### ISSUE TITLE
Impossible to upgrade gmusic-script

### ISSUE THREAD

**Issue by ManuCart** [thebigmunch/gmusicapi-scripts#71]
````
sudo pip3 install --upgrade gmusicapi-scripts

Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python3/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name 'IncompleteRead'
pi@raspberrypi:~$ Traceback (most recent call last):
-bash: erreur de syntaxe près du symbole inattendu « most »
pi@raspberrypi:~$   File "/usr/bin/pip3", line 9, in <module>
-bash: erreur de syntaxe près du symbole inattendu « newline »
pi@raspberrypi:~$     load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
-bash: erreur de syntaxe près du symbole inattendu « 'pip==1.5.6', »
pi@raspberrypi:~$   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
-bash: File : commande introuvable
pi@raspberrypi:~$     return get_distribution(dist).load_entry_point(group, name)
-bash: erreur de syntaxe près du symbole inattendu « ( »
pi@raspberrypi:~$   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
-bash: File : commande introuvable
pi@raspberrypi:~$     return ep.load()
-bash: erreur de syntaxe près du symbole inattendu « ( »
pi@raspberrypi:~$   File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2229, in load
-bash: File : commande introuvable
pi@raspberrypi:~$     return self.resolve()
-bash: erreur de syntaxe près du symbole inattendu « ( »
````

**Comment by thebigmunch** [comment]
That error message has nothing to do with gmusicapi-scripts; it clearly shows an error originating in your copy of pip. Start by updating pip and go from there. It looks like it's quite out of date.

**Comment by ManuCart** [comment]
OK thanks working after
````
sudo easy_install3 -U pip
````
