### ISSUE TITLE
Script fails to download entire library if song title contains bare U+00B4

### ISSUE THREAD

**Issue by Outurnate** [thebigmunch/gmusicapi-scripts#76]
I have a song in my library that uses an acute accent in place of an apostrophe.  When gmsync tries to copy this file down, it crashes with the stacktrace shown below

    Traceback (most recent call last):
      File "/data/music_service/venv/bin/gmsync", line 11, in <module>
        sys.exit(main())
      File "/data/music_service/venv/lib/python3.5/site-packages/gmusicapi_scripts/gmsync.py", line 150, in main
        mmw.download(songs_to_download, template=cli['output'])
      File "/data/music_service/venv/lib/python3.5/site-packages/gmusicapi_wrapper/decorators.py", line 22, in wrapper
        return function(*args, **kwargs)
      File "/data/music_service/venv/lib/python3.5/site-packages/gmusicapi_wrapper/musicmanager.py", line 215, in download
        for result in self._download(songs, template):
      File "/data/music_service/venv/lib/python3.5/site-packages/gmusicapi_wrapper/musicmanager.py", line 181, in _download
        shutil.move(temp.name, filepath)
      File "/data/music_service/venv/lib/python3.5/shutil.py", line 527, in move
        if os.path.isdir(dst):
      File "/data/music_service/venv/lib/python3.5/genericpath.py", line 42, in isdir
        st = os.stat(s)
    UnicodeEncodeError: 'ascii' codec can't encode character '\xb4' in position 63: ordinal not in range(128)

I'm going to try to correct the song title, but it'd be nice if gmsync could replace invalid chars with some other character ('_' maybe?), or at the very least allow the batch to continue.

**Comment by thebigmunch** [comment]
That isn't an invalid character. And the error is happening in Python, not my code. When other users have run into this, it's been a poor shell encoding Make sure it is some variant of UTF8.

**Comment by Outurnate** [comment]
That was it!  Appreciate the help!  I still hadn't run `locale-gen`.  Once I had selected a locale and run it, gmsync had no trouble

Awesome work on these tools!  They really do just work
