### ISSUE TITLE
Gmsync started failing

### ISSUE THREAD

**Issue by Forceflow** [thebigmunch/gmusicapi-scripts#78]
Was working fine until a few days ago - ubuntu 16.10.
``
MusicManagerWrapper authentication failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi_wrapper/musicmanager.py", line 54, in login
    if not self.api.login(oauth_credentials=oauth_cred, uploader_id=uploader_id):
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 170, in login
    self._perform_upauth(uploader_id, uploader_name))
  File "/usr/local/lib/python3.5/dist-packages/gmusicapi/clients/musicmanager.py", line 207, in _perform_upauth
    raise OSError('a valid MAC could not be determined.'
OSError: a valid MAC could not be determined. Provide uploader_id (and be sure to provide the same one on future runs).
``

**Comment by thebigmunch** [comment]
Not an issue with the scripts, and you've already commented on the gmusicapi issue.
