### ISSUE TITLE
Error on upload

### ISSUE THREAD

**Issue by jacopomarcovaldi** [thebigmunch/gmusicapi-scripts#79]
Hi,
i am using your script for about 1 year.
Yesterday suddenly it return this error during the upload process:

> Traceback (most recent call last):
  File "/usr/local/bin/gmupload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi_scripts/gmupload.py", line 126, in main
    mmw.upload(songs_to_upload, enable_matching=cli['match'], delete_on_success=cli['delete-on-success'])
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi_wrapper/decorators.py", line 22, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi_wrapper/musicmanager.py", line 303, in upload
    for result in self._upload(filepaths, enable_matching=enable_matching, transcode_quality=transcode_quality):
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi_wrapper/musicmanager.py", line 256, in _upload
    filepath, enable_matching=enable_matching, transcode_quality=transcode_quality
  File "<decorator-gen-74>", line 2, in upload
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/utils/utils.py", line 616, in wrapper
    return function(*args, **kw)
  File "<decorator-gen-73>", line 2, in upload
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/utils/utils.py", line 593, in wrapper
    return function(*args, **kw)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/clients/musicmanager.py", line 578, in upload
    musicmanager.GetUploadSession.process_session(session)
  File "/usr/local/lib/python3.4/dist-packages/gmusicapi/protocol/musicmanager.py", line 463, in process_session
    ['completionInfo']['customerSpecificInfo']['ResponseCode'])
KeyError: 'customerSpecificInfo'

May be google changed somenthing? 
Can you help me?

thank you :)

**Comment by thebigmunch** [comment]
See the [gmusicapi issue](https://github.com/simon-weber/gmusicapi/issues/570).
