### ISSUE TITLE
__init__() takes at most 4 positional arguments (5 given)

### ISSUE THREAD

**Issue by xdragonforce** [thebigmunch/gmusicapi-scripts#80]
Get these when I run any of the scripts. Auth link is given but program crashes no matter what I paste in.

`gmsync
__init__() takes at most 4 positional arguments (5 given)

Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?client_id=652850857958.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusicmanager&access_type=offline&response_type=code
Follow the prompts, then paste the auth code here and hit enter:
Traceback (most recent call last):
  File "./gmsync", line 11, in <module>
    sys.exit(main())
  File "/media/sdi1/stew/.local/lib/python3.6/site-packages/gmusicapi_scripts/gmsync.py", line 110, in main
    mmw.login(oauth_filename=cli['cred'], uploader_id=cli['uploader-id'])
  File "/media/sdi1/stew/.local/lib/python3.6/site-packages/gmusicapi_wrapper/musicmanager.py", line 56, in login
    self.api.perform_oauth(storage_filepath=oauth_cred)
  File "/media/sdi1/stew/.local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 101, in perform_oauth
    credentials = flow.step2_exchange(code)
  File "/media/sdi1/stew/.local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/media/sdi1/stew/.local/lib/python3.6/site-packages/oauth2client/client.py", line 2089, in step2_exchange
    raise FlowExchangeError(error_msg)
oauth2client.client.FlowExchangeError: invalid_requestMissing required parameter: code
`

**Comment by simon-weber** [comment]
Is is possible you've got an old version of gmusicapi? What's the output of `pip freeze`?

**Comment by xdragonforce** [comment]
![image](https://user-images.githubusercontent.com/1136276/31563122-c4aea9b2-b055-11e7-85c4-ba38dbe0a104.png)

Thought that could be the problem, but I tried the pip3 install version, then cloned directly from github!

**Comment by simon-weber** [comment]
Huh. And what about `python -c 'import gmusicapi; print gmusicapi.__version__; print gmusicapi.__file__'`?

**Comment by xdragonforce** [comment]
![image](https://user-images.githubusercontent.com/1136276/31563304-61164d8c-b056-11e7-8ab5-dd8eadd483bc.png)

**Comment by simon-weber** [comment]
ah, python3. try `python -c 'import gmusicapi; print(gmusicapi.__version__); print(gmusicapi.__file__)'` instead.

**Comment by xdragonforce** [comment]
![image](https://user-images.githubusercontent.com/1136276/31563415-db1996f2-b056-11e7-9f4d-8b4dbc9e3e41.png)

**Comment by simon-weber** [comment]
Huh, that all looks fine. Maybe @thebigmunch will have some other ideas.

**Comment by simon-weber** [comment]
This is fixed in https://github.com/simon-weber/gmusicapi/issues/613. It was only a warning and shouldn't have affected anything, afaict.
