### ISSUE TITLE
MusicManagerWrapper authentication failed.

### ISSUE THREAD

**Issue by ThisIsSet-L** [thebigmunch/gmusicapi-scripts#82]
Unable to authenticate using OAuth (running latest stable as of posting).

```
$ gmupload
Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?redirect_uri=...
Follow the prompts, then paste the auth code here and hit enter: **************************
MusicManagerWrapper authentication failed.
```
Happens when running `gmsync` too.

**Comment by alex-phillips** [comment]
Same for me.

**Comment by ozamorowski** [comment]
Same here with python3.

**Comment by alex-phillips** [comment]
Fixed the issue with mine. Ended up I had too many "devices" authenticated with my account. Removed a few from my Google music account and it start running fine again.

**Comment by gongfarmer** [comment]
Same issue here.  
I have only one device associated with my account.
Debug output:
`fraser@fhanson-mac-0:~$ gmupload
/usr/local/lib/python3.6/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /Users/fraser/Library/Application Support/gmusicapi/oauth.cred: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))
__init__() takes at most 4 positional arguments (5 given)

Visit the following url:
 https://accounts.google.com/o/oauth2/v2/auth?client_id=652850857958.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmusicmanager&access_type=offline&response_type=code
Follow the prompts, then paste the auth code here and hit enter: *********************************************************
Traceback (most recent call last):
  File "/usr/local/bin/gmupload", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/gmusicapi_scripts/gmupload.py", line 79, in main
    mmw.login(oauth_filename=cli['cred'], uploader_id=cli['uploader-id'])
  File "/usr/local/lib/python3.6/site-packages/gmusicapi_wrapper/musicmanager.py", line 56, in login
    self.api.perform_oauth(storage_filepath=oauth_cred)
  File "/usr/local/lib/python3.6/site-packages/gmusicapi/clients/musicmanager.py", line 101, in perform_oauth
    credentials = flow.step2_exchange(code)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oauth2client/client.py", line 2089, in step2_exchange
    raise FlowExchangeError(error_msg)
oauth2client.client.FlowExchangeError: invalid_grantBad Request`

**Comment by antonkomarev** [comment]
Same error here. And I have only one device associated with my account.
